apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  DB_HOST: {{ .Values.db.host | b64enc | quote }}
  DB_NAME: {{ .Values.db.name | b64enc | quote }}
